### ISSUE TITLE
missing files

### ISSUE THREAD

**Issue by welcomeking** [amanjeetsingh150/UberCarAnimation#1]
there is no string file or  res/values/google_maps_api.xm

**Comment by amanjeetsingh150** [comment]
Hey @welcomeking ,

Yes I previously gitignore those files due to presence of my keys there I have now added them. So to run your app just add your google maps directions api key in <a href="https://github.com/amanjeetsingh150/UberCarAnimation/blob/master/app/src/main/res/values/strings.xml">strings.xml</a> and google maps key in <a href="https://github.com/amanjeetsingh150/UberCarAnimation/blob/master/app/src/debug/res/values/google_maps_api.xml">google_maps_api.xml</a>. For convenience I have added a TODO there just follow them. Do connect if you face any further issues.

Thanks.
