### ISSUE TITLE
Camera Not Zooming in out

### ISSUE THREAD

**Issue by Hassankhan2015** [amanjeetsingh150/UberCarAnimation#6]
Hello Sir Thanks for such nice example, it is really helpful and useful. I have issue regarding the camera zoom in and out. When the car is moving camera is just moving with the car. I want to zoom in and zoom the map. I tried to figure out from the code but failed to do it. Please can you brief me regarding this issue.

**Comment by amanjeetsingh150** [comment]
@Hassankhan2015 sure will look into this issue and update the project. Will try do this ASAP.

**Comment by sanjaykumarm** [comment]
Waiting for this feature.

**Comment by amanjeetsingh150** [comment]
Hey @sanjaykumarm @Hassankhan2015 I have addressed this issue please do check. The problem was there in <code>moveCamera</code> function. It creates a lock over your maps camera. Do check and revert.
I am closing the issue as it is resolved in my devices. Feel free to reopen issue if anything came up.

Thanks :+1:

**Comment by sanjaykumarm** [comment]
@amanjeetsingh150 I will check once I got a chance, and really thank you so much for your quick and hard work. It is helping so many developers. Keep up good work.
